added action-mapper, view-all-viz component and container, reducer, a…
revaturelabs/Curricula-UI pull request #24
Opened 2020-01-10 22:23 UTC by wes-o

…nd remote config follows: previous pull request #11

2020-01-10 22:24 UTC, wes-o reviewed
I apologize, file: ViewAllVizAction has lengthy commented out section
if necessary, i'll commit again with out these comments

2020-01-10 22:58 UTC, Abatson commented on src/reducers/index.ts
> +}
You only need one variable, of type IVizState, it will hold visualizations and newVis

2020-01-10 22:58 UTC, Abatson commented on src/remote/CurriculaClient.ts
> +    baseURL: (environment.dev || environment.prod),
Same thing I told zia, this will always use the dev choice

2020-01-10 22:59 UTC, Abatson commented on src/components/view-all-viz-component/ViewAllVizContainer.tsx
> +        allVisualizations: state.visualizationSet.visualizations
Don;t foget to change thi when you rework IState in reducers/index

2020-01-10 23:00 UTC, Abatson requested changes
Read comments

2020-01-11 18:09 UTC, closed without merging

2020-01-12 16:07 UTC, wes-o commented
👍